name: Deploy DAGs to GCP Composer

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour on the hour (UTC)
  workflow_dispatch:       # Optional: Manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up gcloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install gcloud CLI components
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: tsda-456117

      - name: Sync DAGs to Cloud Composer bucket
        run: |
          gcloud config set project tsda-456117
          gsutil -m rsync -r dags/ gs://us-central1-airflow-v1-289d3fea-bucket/dags/
